spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/PwCCloud
        password: admin
        driver-class-name: org.postgresql.Driver
        username: postgres
metadata:
    version: 1
